# Generated by Django 5.1 on 2024-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="query",
            options={"verbose_name": "Запрос", "verbose_name_plural": "Запросы"},
        ),
        migrations.AlterField(
            model_name="query",
            name="cadastral_number",
            field=models.CharField(max_length=255, verbose_name="Кадастровый номер"),
        ),
        migrations.AlterField(
            model_name="query",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время запроса"
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="latitude",
            field=models.IntegerField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="query",
            name="longitude",
            field=models.IntegerField(verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="query",
            name="result",
            field=models.BooleanField(null=True, verbose_name="Результат запроса"),
        ),
    ]
